services:
  front-end:
    image: weaveworksdemos/front-end:0.3.12
    ports:
      - "8079:8079"

  catalogue:
    image: killuazoldyckk/catalogue:1cebb20

  carts:
    image: weaveworksdemos/carts:0.4.8

  user:
    image: weaveworksdemos/user:0.4.4

  catalogue-db:
    image: weaveworksdemos/catalogue-db:0.3.0

  user-db:
    image: weaveworksdemos/user-db:0.4.0

  redis:
    image: redis:alpine

